/**
 * Turn a non-2xx `Response` into something the Notice component can show.
 *
 * Why this exists
 * ───────────────
 * Admin fetch paths each rolled their own error handling, and two of them
 * assumed the body was JSON. It often is not: a 502/503/504 from the platform
 * is generated by the edge, not by the route, and carries an HTML body. On
 * those, `await res.json()` throws, and the thrown SyntaxError ("Unexpected
 * token '<'") is what reached the operator — when anything reached them at
 * all. That is how a five-month-old upload failure stayed invisible.
 *
 * The contract here: a failure always produces a title. When the route
 * answered with its own `error`/`hint`/`code`, those are used. When there is
 * no JSON body to read, the HTTP status is reported instead, in words.
 *
 * Client-safe: no imports, no server-only APIs.
 */

export interface HttpFailure {
  /** One line, fit to show as a Notice title. */
  title: string;
  /** Optional second line: the route's hint, and its error code. */
  detail?: string;
  /** The HTTP status, for callers that want to branch on it. */
  status: number;
}

/** Statuses generated upstream of the route, where no JSON body is expected. */
const GATEWAY_STATUS: Record<number, string> = {
  502: 'The server returned a bad-gateway error (502)',
  503: 'The server is unavailable (503)',
  504: 'The server timed out (504)',
};

/**
 * Read a JSON body without throwing on an empty, truncated or HTML response.
 * Returns `{}` when there is nothing parseable — never rejects.
 */
export async function readErrorBody(res: Response): Promise<Record<string, unknown>> {
  try {
    const body = await res.json();
    return body && typeof body === 'object' ? (body as Record<string, unknown>) : {};
  } catch {
    return {};
  }
}

/**
 * Describe a failed response.
 *
 * `action` names what was being attempted, in the operator's terms, and is
 * used only when the server gave us nothing to say — e.g. "Cover image upload
 * failed".
 */
export async function describeHttpFailure(res: Response, action: string): Promise<HttpFailure> {
  return describeErrorBody(await readErrorBody(res), res.status, action);
}

/**
 * The same description, for callers that have already read the body (because
 * they also need something else out of it, such as the scraper's `evidence`).
 */
export function describeErrorBody(
  body: Record<string, unknown>,
  status: number,
  action: string,
): HttpFailure {
  const serverError = typeof body.error === 'string' && body.error ? body.error : null;
  const hint = typeof body.hint === 'string' && body.hint ? body.hint : null;
  const code = typeof body.code === 'string' && body.code ? body.code : null;

  // The route answered for itself — prefer its wording over ours.
  if (serverError) {
    return {
      title: serverError,
      detail: [hint, code ? `Code: ${code}` : null].filter(Boolean).join(' · ') || undefined,
      status,
    };
  }

  // No JSON body. Report the status, which is the only fact we have.
  const gateway = GATEWAY_STATUS[status];
  return {
    title: gateway ? `${action} — ${gateway}.` : `${action} — HTTP ${status}.`,
    detail: gateway
      ? 'This came from the hosting platform, not the application. Nothing was saved. Retry in a moment; if it persists, check the server logs.'
      : 'The server returned no error details. Nothing was saved.',
    status,
  };
}
